#!/usr/bin/env bash
set -e

usage() {
  echo "Usage: gh contrib [--style <style>]"
}

data=( $(gh api graphql -f query='{
  viewer {
    contributionsCollection {
      contributionCalendar {
        weeks {
          contributionDays {
            color
            contributionCount
          }
        }
      }
    }
  }
}' --cache 24h --jq '..|.color?, .contributionCount?' | grep .) )

style=block
while [ $# -gt 0 ]; do
  case "$1" in
    -s|--style)
      style="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 1
      ;;
  esac
done

case "$style" in
  block)
    block_full="█"
    block_empty="$block_full";;
  *)
    echo "error: style '$style' not recognized" >&2
    exit 1;;
esac

get_level() {
  if [ "$1" -eq 0 ]; then
    echo "0"
  elif [ "$1" -lt 2 ]; then
    echo "1"
  elif [ "$1" -lt 4 ]; then
    echo "2"
  elif [ "$1" -lt 8 ]; then
    echo "3"
  else
    echo "4"
  fi
}

get_color() {
  case "$1" in
    0)
      echo -e "\033[48;5;235m";;
    1)
      echo -e "\033[48;5;243m";;
    2)
      echo -e "\033[48;5;102m";;
    3)
      echo -e "\033[48;5;34m";;
    4)
      echo -e "\033[48;5;22m";;
  esac
}

display_label() {
  if [ "$1" -eq 0 ] && [ "$2" -eq 2 ]; then
    echo -n "Sun"
  elif [ "$1" -eq 1 ] && [ "$2" -eq 2 ]; then
    echo -n "Mon"
  elif [ "$1" -eq 2 ] && [ "$2" -eq 2 ]; then
    echo -n "Tue"
  elif [ "$1" -eq 3 ] && [ "$2" -eq 2 ]; then
    echo -n "Wed"
  elif [ "$1" -eq 4 ] && [ "$2" -eq 2 ]; then
    echo -n "Thu"
  elif [ "$1" -eq 5 ] && [ "$2" -eq 2 ]; then
    echo -n "Fri"
  elif [ "$1" -eq 6 ] && [ "$2" -eq 2 ]; then
    echo -n "Sat"
  elif [ "$2" -eq 0 ]; then
    printf " %2d" "$1"
  else
    echo -n "   "
  fi
}

space=" "
if [ -t 1 ] && [ "$(tput cols)" -lt 102 ]; then
  space=""
fi



month_labels=(" J" " F" " M" " A" " M" " J" " J" " A" " S" " O" " N" " D")

for d in $(seq 0 6); do
  display_label $d 2
  for w in $(seq 0 51); do
    index=$((w * 14 + d * 2))
    count="${data[index + 1]}"
    level=$(get_level "$count")
    color="$(get_color "$level")"

    if [ "$d" -eq 0 ] && [ "$w" -eq 0 ]; then
      printf "\n"
    fi

    if [ "$d" -eq 0 ]; then
      month_index=$((w % 12))
      month_label=${month_labels[month_index]}
      printf "%s" "$month_label"
    fi

    printf "%s%s\e[0m%s" "$color" "$block_full" "$space"
  done
  printf "\n"
done
printf "\n"
